apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "zDZ6lBw2m1iYULkid/2UjgdDjNb4umUIlwmtKAQ0e+Ty80XIZqNzugjxu/jJ4VbL\nteCiXGnLjXhMuaP0N03CBNTZKsY1P4l7iRj/65Sho1S62FLg9UBJh3auxzq5yVlT\nfpoVItAawNqkiRHUMsEgvCISlwIrVtRQfgVztzv1YZI="
